doc: correct `uses` in README
mbta/workflows pull request #3
Opened 2022-08-11 17:19 UTC by paulswartz

2022-08-11 17:22 UTC, mzappitello commented on README.md
> +    uses: mbta/workflows/.github/workflows/deploy-ecs.yml@main
might as well catch the missing `'` on line 27 while we're here.

2022-08-11 18:35 UTC, mzappitello requested changes

2022-08-11 18:35 UTC, mzappitello commented on README.md
> +    uses: mbta/workflows/.github/workflows/deploy-ecs.yml@main
might as well catch the missing ' on line 27 while we're here.

2022-08-12 14:22 UTC, losvedir approved these changes
Thanks!

2022-08-12 14:37 UTC, merged